steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE}:$REVISION_ID', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE}:$REVISION_ID']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'beta'
  - 'run'
  - 'deploy'
  - '${_SERVICE}'
  - '--image'
  - 'gcr.io/$PROJECT_ID/${_SERVICE}:$REVISION_ID'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--project'
  - '$PROJECT_ID'
  - '--allow-unauthenticated'
#- name: 'gcr.io/cloud-builders/git'
#  args:
#  - 'init'
#- name: 'gcr.io/cloud-builders/git'
#  args:
#  - 'remote'
#  - 'set-url'
#  - 'origin'
#  - '${_GITHUB_URL}'
#- name: 'gcr.io/cloud-builders/npm:current'
#  args:
#    - 'run'
#    - 'gren-release'
#  env:
#    - 'GREN_GITHUB_TOKEN=${_GITHUB_TOKEN}'
images:
  - gcr.io/$PROJECT_ID/${_SERVICE}:$REVISION_ID
