steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  timeout: 25s
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  timeout: 5s
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE}:$REVISION_ID', '.']
  timeout: 10s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE}:$REVISION_ID']
  timeout: 10s
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'beta'
  - 'run'
  - 'deploy'
  - '${_SERVICE}'
  - '--image'
  - 'gcr.io/$PROJECT_ID/${_SERVICE}:$REVISION_ID'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--project'
  - '$PROJECT_ID'
  - '--allow-unauthenticated'
  timeout: 25s
- name: 'gcr.io/cloud-builders/node:current'
  args:
    - 'run'
    - 'gren-release'
  env:
    - 'GREN_GITHUB_TOKEN=${_GITHUB_TOKEN}'
  timeout: 10s
images:
  - gcr.io/$PROJECT_ID/${_SERVICE}:$REVISION_ID
