steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE}']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'beta'
  - 'run'
  - 'deploy'
  - '${_SERVICE}'
  - '--allow-unauthenticated'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--image'
  - 'gcr.io/$PROJECT_ID/${_SERVICE}'
images:
  - gcr.io/$PROJECT_ID/${_SERVICE}
