name: Labeler
on:
  pull_request:
    branches:
      - master
    paths:
      - environments/dev/*
      - modules/*
jobs:
  pr_labeler:
    name: PR Labeler
    runs-on: ubuntu-18.04
    steps:
      - name: Set PR label
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
        uses: actions/labeler@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
