name: 'Pull Request title rules'
description: 'Github action to enforce Pull Request title conventions'
author: 'deepakputhraya'
inputs:
  regex:
    description: 'Regex to validate the pull request title'
    default: '^(feat|fix)\/master\/.+'
  allowed_prefixes:
    description: 'Comma separated list of prefix allowed to be used in title. eg: feature,hotfix,JIRA-'
    default: 'feat/master,feat/fix'
  prefix_case_sensitive:
    description: 'Are the allowed prefixes case sensitive?'
    default: true
  min_length:
    description: 'Min length of title'
    default: 5
  max_length:
    description: 'Max length of title. -1 to ignore the rule'
    default: -1

runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
