name: PR naming enforcement
on:
  pull_request:
    branches:
      - master
jobs:
  pr_naming:
    name: PR naming
    runs-on: ubuntu-latest
    steps:
      - name: Checks PR name
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^FEATURE|FIX|ENHANCEMENT: .+$'
          allowed_prefixes: 'FEATURE FIX ENHANCEMENT'
          prefix_case_sensitive: true
          min_length: 15
          max_length: -1
