name: PR naming enforcement
on:
  pull_request:
    branches:
      - master
jobs:
  pr_naming:
    name: PR naming
    runs-on: ubuntu-latest
    steps:
      - name: Checks PR name
        uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(FEATURE|FIX|ENHANCEMENT|CHORE|REFACTOR): [a-zA-Z 0-9._-]+$'
          allowed_prefixes: 'FEATURE,FIX,ENHANCEMENT,CHORE,REFACTOR'
          prefix_case_sensitive: true
          min_length: 7
          max_length: -1
